export const TITLE = "Seamless, Privacy-Preserving, "
export const TITLE_COLORED = "Whitelisting "
export const TITLE_LAST = "for DeFi"
export const DESCRIPTION = "Access verified TradFi-backed trading pools with Keyring's protocol-agnostic whitelisting and AML/KYC."
export const CTA_TEXT = "Keep your identity in complete anonymity"
export const CTA_BUTTON = "Join the Waitlist"
export const CTA_BUTTON_URL = "https://0d07oori297.typeform.com/to/PF5a05ot"